
package org.jboss.samples.onewayws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-04/11/2011 03:11 PM(mockbuild)-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PingService", targetNamespace = "http://localhost.jboss.sample/ws/ping", wsdlLocation = "file:/home/taneem/Desktop/jboss-eap-5.1.2/jboss-as/bin/PingService4507476042409347928.wsdl")
public class PingService
    extends Service
{

    private final static URL PINGSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.jboss.samples.onewayws.client.PingService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.jboss.samples.onewayws.client.PingService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/taneem/Desktop/jboss-eap-5.1.2/jboss-as/bin/PingService4507476042409347928.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/taneem/Desktop/jboss-eap-5.1.2/jboss-as/bin/PingService4507476042409347928.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PINGSERVICE_WSDL_LOCATION = url;
    }

    public PingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PingService() {
        super(PINGSERVICE_WSDL_LOCATION, new QName("http://localhost.jboss.sample/ws/ping", "PingService"));
    }

    /**
     * 
     * @return
     *     returns Ping
     */
    @WebEndpoint(name = "PingPort")
    public Ping getPingPort() {
        return super.getPort(new QName("http://localhost.jboss.sample/ws/ping", "PingPort"), Ping.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ping
     */
    @WebEndpoint(name = "PingPort")
    public Ping getPingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost.jboss.sample/ws/ping", "PingPort"), Ping.class, features);
    }

}
