
package org.jboss.samples.onewayws.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-04/11/2011 03:11 PM(mockbuild)-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Ping", targetNamespace = "http://localhost.jboss.sample/ws/ping")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ping {


    /**
     * 
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "ping", targetNamespace = "http://localhost.jboss.sample/ws/ping", className = "org.jboss.samples.onewayws.client.Ping_Type")
    public void ping();

}
